---
dotfile_files:
  - .ackrc
  - .agignore
  - .alacritty.yml
  - .bash
  - .bash_profile
  - .clipper.json
  - .config/ranger
  - .ghci
  - .gitattributes
  - .gitignore
  - .gitk
  - .gvimrc
  - .hammerspoon
  - .hgrc
  - .inputrc
  - .lbdbrc
  - .npmrc
  - .pypirc
  - .rdebugrc
  - .rspec
  - .screenrc
  - .tmux.conf
  - .urlview
  - .vim
  - .zsh
  - .zshenv
  - .zshrc

dotfile_templates:
  - .config/karabiner/karabiner.json
  - .gemrc
  - .gitconfig
  - .hammerspoon/iterm.lua

git_user_email: '{{"peter@schussheim.com" if lookup("env", "USER") == "pds" else ""}}'
git_user_name: '{{"Peter Schussheim" if lookup("env", "USER") == "pds" else ""}}'
