---
- import_tasks: bundle.yml
  when: update_vim_bundle

- import_tasks: build.yml

- import_tasks: masochist.yml
  when: install_masochist_vim_dependencies

- import_tasks: nvim.yml

- import_tasks: deoplete.yml
  when: install_deoplete_extensions
