---
# iTerm will create some of these on first run, but we specify all here
# for completeness.
- name: iterm | make directories
  file: path="{{ item }}" state=directory
  with_items:
    - "~/Library/Application Support/iTerm2"
    - "~/Library/Application Support/iTerm2/DynamicProfiles"
    - "~/Library/Application Support/iTerm2/Sources"

- name: iterm | link Dynamic Profiles
  file: state=link src="{{ item }}" dest="~/Library/Application Support/iTerm2/DynamicProfiles/{{ item | basename }}"
  with_fileglob:
    - "roles/iterm/files/DynamicProfiles/*.json"

- name: iterm | link Sources
  file: state=link src="{{ item }}" dest="~/Library/Application Support/iTerm2/Sources/{{ item | basename }}"
  with_fileglob:
    - "roles/iterm/files/Sources/*.json"

- name: iterm | check switchable symbolic links
  stat: path="~/Library/Application Support/iTerm2/DynamicProfiles/{{ item.dest }}"
  with_items: '{{ iterm_dynamic_profiles.retina }}'
  register: dynamic_profiles_stat_info
  changed_when: false

# We only link these ones if they don't already exist;
# once created, Hammerspoon manages the links.
- name: iterm | set up switchable symbolic links
  file:
    dest="~/Library/Application Support/iTerm2/DynamicProfiles/{{ item.1.dest }}"
    src="~/Library/Application Support/iTerm2/Sources/{{ item.1.src }}"
    state=link
  with_indexed_items: '{{ iterm_dynamic_profiles.retina }}'
  when: not dynamic_profiles_stat_info.results[item.0].stat.exists
